server:
  port: 8081

logging:
  level:
    root: debug

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      access-token-validity-seconds: 60
      refresh-token-validity-seconds: 600


spring:
  security:
    user:
      name: name
      password: password
    oauth2:
      client:
        clientId: client
        clientSecret: secret
      scope: read,write
      grantType: client_credentials
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
      resource:
        tokenInfoUri: http://localhost:8081/oauth/token